# Generated by Django 4.0.3 on 2022-03-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='user',
            field=models.TextField(),
        ),
    ]
